"""initial migration

Revision ID: 060313119d7a
Revises: 
Create Date: 2025-01-08 04:09:49.523608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060313119d7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_number', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('student_number')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('credit', sa.Float(), nullable=False),
    sa.Column('akts', sa.Integer(), nullable=False),
    sa.Column('midterm_percentage', sa.Integer(), nullable=False),
    sa.Column('others_percentage', sa.Integer(), nullable=False),
    sa.Column('final_percentage', sa.Integer(), nullable=False),
    sa.Column('midterm_grade', sa.Float(), nullable=True),
    sa.Column('others_grade', sa.Float(), nullable=True),
    sa.Column('final_grade', sa.Float(), nullable=True),
    sa.Column('total_grade', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=2), nullable=True),
    sa.Column('contribution_point', sa.Float(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course')
    op.drop_table('user')
    # ### end Alembic commands ###
